// HelloATLProject.idl: HelloATLProject의 IDL 소스
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(HelloATLProject.tlb) 및 마샬링 코드를 생성합니다.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(712ec3e7-eaed-4dcd-9afc-ae9c3f9f5efc),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IATLSimpleObject : IDispatch
{
};
[
	uuid(e5467b0f-409b-4566-a638-955ede39099b),
	version(1.0),
]
library HelloATLProjectLib
{
	importlib("stdole2.tlb");
	[
		uuid(9f811706-c910-458e-b526-0954b7b14ec6)
	]
	coclass ATLSimpleObject
	{
		[default] interface IATLSimpleObject;
	};
};

import "shobjidl.idl";
